#let counter-chapter = counter("chapter")
#let counter-title = counter("title")
#let counter-question = counter("question")
#let counter-explain = counter("explain")
#let counter-placeholder = counter("placeholder")
